name: long running tasks
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  long-running-task:
    strategy:
      matrix:
        each: [5, 10]
        until: [20, 120, 300]
    name: "long run task each ${{each}} until ${{until}}"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: check out
      - uses: actions/setup-go@v2
        name: setup go
        with:
          go-version: "1.17.2"
      - run: make run -each "${{each}}" -until "${{until}}"
        name: "long task each ${{each}} until ${{until}}"
